### PR TITLE
DDT-116: Added transport document test data for eBL

### PR DESCRIPTION
**Pull request by mp-assco**

### CODE REVIEW

**Review by HenrikHL — CHANGES_REQUESTED** [review]
I don't think this will work. We need to have a separate branch based in IM 3.0.1 for this test data to be added

**Comment by douradofrazer** [comment]
But we do not know which commit would be considered as 3.0.1.

**Comment by mp-assco** [comment]
> I don't think this will work. We need to have a separate branch based in IM 3.0.1 for this test data to be added

I don't understand. Why would it work? What have we defined as IM 3.0.1?

**Comment by HenrikHL** [comment]
My bad - I can see that eBL is linked to IM v3.1. This commit needs to go into IM 3.1 and not into master

**Comment by mp-assco** [comment]
> My bad - I can see that eBL is linked to IM v3.1. This commit needs to go into IM 3.1 and not into master

I don't think moving this to IM 3.1 would make sense since these tests are made with the current datamodel that we intent to update eBL into at some point.

**Pull request closed without merging**
